<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Titus 11_MuiButtonBase-root-4927 MuiIconButton-root-4919 jss4946</name>
   <tag></tag>
   <elementGuidId>3b1daf99-ebba-430b-802c-f6ed450a61fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'MuiButtonBase-root-4927 MuiIconButton-root-4919 jss4946' and @type = 'button' and @title = 'Add a Row']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root-4927.MuiIconButton-root-4919.jss4946</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>410acecc-371b-403e-a45a-a99616d0a76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-4927 MuiIconButton-root-4919 jss4946</value>
      <webElementGuid>1490f7c0-ef45-47f0-9d8a-36cc963b1ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53bddbef-7b9f-4b10-966b-a47a4bc1b028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ff6f685-9f59-457e-8e5f-7647d9fc9261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add a Row</value>
      <webElementGuid>7c90f82f-ae89-44de-b820-146456886ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-1-1-rtc9&quot;)/div[@class=&quot;jss256&quot;]/div[1]/div[@class=&quot;MuiGrid-root-4773 jss4771 MuiGrid-container-4774 MuiGrid-align-items-xs-center-4782 MuiGrid-justify-content-xs-space-between-4793&quot;]/div[@class=&quot;MuiGrid-root-4773 MuiGrid-item-4775&quot;]/div[@class=&quot;MuiGrid-root-4773 jss4906 MuiGrid-container-4774 MuiGrid-align-items-xs-center-4782 MuiGrid-justify-content-xs-flex-end-4792&quot;]/div[@class=&quot;jss4944&quot;]/div[2]/button[@class=&quot;MuiButtonBase-root-4927 MuiIconButton-root-4919 jss4946&quot;]</value>
      <webElementGuid>d5b85c4f-e6b2-4abd-89ed-2dd2b860f7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>a93e95ed-3a1e-407a-93ba-bb454464f207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-1-1-rtc9']/div/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>ca555fdb-3120-4d34-891b-0c3e8b8ff191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titus 1:1'])[1]/following::button[5]</value>
      <webElementGuid>c7a573a3-f1bc-46c2-a88a-2197fd4ba311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OccurrenceNote'])[5]/following::button[5]</value>
      <webElementGuid>fcdd5e99-9946-4fd1-a07b-46617bc8a702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>cb54999b-d004-4577-9755-9dc01440ec5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Add a Row']</value>
      <webElementGuid>0e88dea1-8223-46ec-8e64-9da265e85cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
