<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Titus 11_Delete new row</name>
   <tag></tag>
   <elementGuidId>9746b3d5-49d1-4991-9ffd-f6363a4247ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42c59790-3052-45cd-bab5-83203a109704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-696 MuiIconButton-root-688 jss714</value>
      <webElementGuid>caf85e02-7ab5-436e-8db1-3401dc3de62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>001e1e32-04d5-48b2-b8ae-5bda55440e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08429ebc-65e8-4374-bddc-c67ea5c87ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete a Row</value>
      <webElementGuid>1f69a877-3fdf-41e1-ad0c-f89457a7c082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header---&quot;)/div[@class=&quot;jss256&quot;]/div[@class=&quot;jss259&quot;]/div[@class=&quot;MuiGrid-root-542 jss540 MuiGrid-container-543 MuiGrid-align-items-xs-center-551 MuiGrid-justify-xs-space-between-562&quot;]/div[@class=&quot;MuiGrid-root-542 MuiGrid-item-544&quot;]/div[@class=&quot;MuiGrid-root-542 jss675 MuiGrid-container-543 MuiGrid-align-items-xs-center-551 MuiGrid-justify-xs-flex-end-561&quot;]/div[@class=&quot;jss712&quot;]/div[3]/button[@class=&quot;MuiButtonBase-root-696 MuiIconButton-root-688 jss714&quot;]</value>
      <webElementGuid>7f7eb7cb-3c81-409e-b119-f4d1fe02be40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[29]</value>
      <webElementGuid>312ca081-00d6-46a9-a3b3-1b3f80aa7bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header---']/div/div/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>71459af9-9b3a-4692-979f-0c3176a325fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titus 1:1'])[2]/following::button[6]</value>
      <webElementGuid>0b9da570-dc4c-4e9e-95e7-e9d3839fe214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='faith'])[3]/following::button[6]</value>
      <webElementGuid>65e0b537-1a28-4c4d-aa0e-8598190f0fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/div/div/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>da120980-7e77-4a62-b22d-326831bbacc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
