<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_empty</name>
   <tag></tag>
   <elementGuidId>9006c66a-582b-4ab8-9374-255b413e27ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='MUIDataTableBodyRow-3']/td[2]/div/div/div/div/div/div[2]/div/pre/code</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;MUIDataTableBodyRow-3&quot;)/td[@class=&quot;MuiTableCell-root-214 MuiTableCell-body-216 jss240&quot;]/div[@class=&quot;jss240&quot;]/div[@class=&quot;cell-3-4 jss252&quot;]/div[@class=&quot;jss257&quot;]/div[@class=&quot;jss253&quot;]/div[@class=&quot;jss259&quot;]/div[@class=&quot;editableWrapper&quot;]/div[@class=&quot;jss274&quot;]/pre[@class=&quot;jss277&quot;]/code[@class=&quot;jss276&quot;][count(. | //*[(text() = '*empty*' or . = '*empty*')]) = count(//*[(text() = '*empty*' or . = '*empty*')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cell-3-4.jss252 > div.jss257 > div.jss253 > div.jss259 > div.editableWrapper > div.jss274 > pre.jss277 > code.jss276</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>811922fb-4f15-401a-89ba-7a9d150078a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss276</value>
      <webElementGuid>9fdfc6ef-8212-491e-bb6c-0feb1f02475d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>edcb83cd-18de-4ebb-830e-d4dad0d7362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8f1a9e8-daa0-4c26-a88b-8ec58daebc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>blockeditable-editable-markdown-pre</value>
      <webElementGuid>2b8a9dc5-e8f7-4e84-bae0-6a584e27826f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*empty*</value>
      <webElementGuid>66b30d20-f65d-485c-8a68-327eae4c18b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MUIDataTableBodyRow-3&quot;)/td[@class=&quot;MuiTableCell-root-214 MuiTableCell-body-216 jss240&quot;]/div[@class=&quot;jss240&quot;]/div[@class=&quot;cell-3-4 jss252&quot;]/div[@class=&quot;jss257&quot;]/div[@class=&quot;jss253&quot;]/div[@class=&quot;jss259&quot;]/div[@class=&quot;editableWrapper&quot;]/div[@class=&quot;jss274&quot;]/pre[@class=&quot;jss277&quot;]/code[@class=&quot;jss276&quot;]</value>
      <webElementGuid>f9c8822a-6e51-4284-b1a2-ce27aed5358a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='MUIDataTableBodyRow-3']/td[2]/div/div/div/div/div/div[2]/div/pre/code</value>
      <webElementGuid>e752e93b-f3ca-4276-a2d5-2429957a9ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[8]/following::code[1]</value>
      <webElementGuid>c7533112-b305-4b3c-8789-1c81a7cf842e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='God'])[10]/following::code[1]</value>
      <webElementGuid>7765e196-666f-477d-8997-f74ec9c86dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[9]/preceding::code[1]</value>
      <webElementGuid>c4f12248-9909-4ba3-a355-bda1df8810cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gkux'])[1]/preceding::code[1]</value>
      <webElementGuid>07e5fa5b-194a-40db-8649-81acf6b27835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/div/div/div/div[2]/div/pre/code</value>
      <webElementGuid>e099f704-52d4-473e-9149-be3073767a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//code[(text() = '*empty*' or . = '*empty*')]</value>
      <webElementGuid>1fd5da41-56ae-4d9f-9587-d07a96a84fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
