<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_unfoldingWord Simplified Textv14_jss5689</name>
   <tag></tag>
   <elementGuidId>c4768fce-0990-46a2-a3c6-ba03db38c4f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss5689</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root-495&quot;]/div[@class=&quot;MuiPaper-root-5634 MuiMenu-paper-493 MuiPopover-paper-496 MuiPaper-elevation8-5645 MuiPaper-rounded-5635&quot;]/ul[@class=&quot;MuiList-root-5662 MuiMenu-list-494 MuiList-padding-5663&quot;]/li[@class=&quot;MuiButtonBase-root-481 MuiListItem-root-5669 MuiMenuItem-root-5666 MuiMenuItem-gutters-5667 MuiListItem-gutters-5674 MuiListItem-button-5675&quot;]/div[@class=&quot;MuiGrid-root-327 MuiGrid-container-328 MuiGrid-justify-xs-space-between-347&quot;]/div[@class=&quot;MuiGrid-root-327 MuiGrid-item-329&quot;]/div[1]/label[@class=&quot;MuiFormControlLabel-root-5677&quot;]/span[@class=&quot;MuiButtonBase-root-481 MuiIconButton-root-473 jss5686 MuiCheckbox-root-5682 MuiCheckbox-colorSecondary-5685 jss5687 Mui-checked MuiIconButton-colorSecondary-478&quot;]/span[@class=&quot;MuiIconButton-label-480&quot;]/input[@class=&quot;jss5689&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/label/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
