<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_unfoldingWord Simplified Text-Russian check box</name>
   <tag></tag>
   <elementGuidId>ee213ec4-a819-4d9d-9308-46a20c976029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2417</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root-496&quot;]/div[@class=&quot;MuiPaper-root-2362 MuiMenu-paper-494 MuiPopover-paper-497 MuiPaper-elevation8-2373 MuiPaper-rounded-2363&quot;]/ul[@class=&quot;MuiList-root-2390 MuiMenu-list-495 MuiList-padding-2391&quot;]/li[@class=&quot;MuiButtonBase-root-482 MuiListItem-root-2397 MuiMenuItem-root-2394 MuiMenuItem-gutters-2395 MuiListItem-gutters-2402 MuiListItem-button-2403&quot;]/div[@class=&quot;MuiGrid-root-328 MuiGrid-container-329 MuiGrid-justify-xs-space-between-348&quot;]/div[@class=&quot;MuiGrid-root-328 MuiGrid-item-330&quot;]/div[1]/label[@class=&quot;MuiFormControlLabel-root-2405&quot;]/span[@class=&quot;MuiButtonBase-root-482 MuiIconButton-root-474 jss2414 MuiCheckbox-root-2410 MuiCheckbox-colorSecondary-2413 jss2415 Mui-checked MuiIconButton-colorSecondary-479&quot;]/span[@class=&quot;MuiIconButton-label-481&quot;]/input[@class=&quot;jss2417&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/label/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
