<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_en_tn</name>
   <tag></tag>
   <elementGuidId>00a49d07-754b-4d87-b263-16d5a24eb09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chip_en_tn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chip_en_tn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8839fcd-d01d-42ce-b6ab-72372091aa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c5d002e-ef0e-48f1-9871-9ffe151bcbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiChip-root MuiChip-colorPrimary MuiChip-deletableColorPrimary MuiChip-deletable</value>
      <webElementGuid>af350c07-9a34-46d3-879c-0f09ff22f80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6aa9195f-5167-4f7c-80ef-46f980379268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chip_en_tn</value>
      <webElementGuid>bff157d8-c941-4753-a524-4f31bfb75b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>repository-item-icon</value>
      <webElementGuid>d8adbc0b-9d7d-4c17-9ccf-e45fbb86559c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>repository-item-icon</value>
      <webElementGuid>f9d26ae0-96d8-4d9b-b04c-16ea05fdf83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>en_tn</value>
      <webElementGuid>dda26c35-1fec-421f-84d9-d24ec6efd79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chip_en_tn&quot;)</value>
      <webElementGuid>e8fadb7e-fd2d-4400-8d57-255fc337bf01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chip_en_tn']</value>
      <webElementGuid>8333af52-bab0-49de-acc0-56f5afb3deb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='App-header']/div/header/div/div[3]/div</value>
      <webElementGuid>b4e6ebc1-668e-4cc4-a665-b9e47b575334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en_tn_57-TIT.tsv'])[1]/following::div[3]</value>
      <webElementGuid>9d456ac0-077f-4198-9401-4e2d2344d759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English - unfoldingWord/en_tn/master'])[1]/preceding::div[4]</value>
      <webElementGuid>b2fe22c0-b106-4d41-9def-4259bdfe8a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>bd00ec3b-822e-47d9-b439-3a3eda8660fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chip_en_tn' and (text() = 'en_tn' or . = 'en_tn')]</value>
      <webElementGuid>5ab9252b-fa9b-4f46-9cb5-18cb1c6f5fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
