<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Old branch Alert</name>
   <tag></tag>
   <elementGuidId>49c897c0-a00e-495b-99bb-2ffcb782d036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='alert-dialog-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alert-dialog-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9b40699e-dadc-48f9-b3dd-824e0b1727ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiDialogContentText-root MuiTypography-body1 MuiTypography-colorTextSecondary</value>
      <webElementGuid>d1d56e54-c5f5-42c2-ade7-87f3d386c57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-dialog-description</value>
      <webElementGuid>9d2318ae-feef-48da-94f7-c67eba48c663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your branch is more than 2 weeks out of date. Older branches are more likely to conflict with newer work. Please contact your administrator to update your branch.</value>
      <webElementGuid>cf119fb6-ef8e-4d88-802c-8ac3a9f06ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-dialog-description&quot;)</value>
      <webElementGuid>5968e143-fb1a-44dd-8e9a-87271ef4f3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='alert-dialog-description']</value>
      <webElementGuid>f761bcaf-554b-4636-80b3-df8aa2f2253b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      <webElementGuid>cc3f7268-f7a9-4acb-89a7-f576d342a383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::p[1]</value>
      <webElementGuid>ca8eb809-15dc-48e4-b101-61c199683bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::p[1]</value>
      <webElementGuid>ae2da880-fa00-4c99-8ca1-0931da3cdeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your branch is more than 2 weeks out of date. Older branches are more likely to conflict with newer work. Please contact your administrator to update your branch.']/parent::*</value>
      <webElementGuid>ef7279cf-8d4c-4db4-a775-23fac8e13c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p</value>
      <webElementGuid>b59d55ed-3367-4fe8-978c-62421af0c1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'alert-dialog-description' and (text() = 'Your branch is more than 2 weeks out of date. Older branches are more likely to conflict with newer work. Please contact your administrator to update your branch.' or . = 'Your branch is more than 2 weeks out of date. Older branches are more likely to conflict with newer work. Please contact your administrator to update your branch.')]</value>
      <webElementGuid>75353b9d-876b-4690-b922-5d372fb8dfc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
