<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>repoText_Row1</name>
   <tag></tag>
   <elementGuidId>3b2be400-0642-441e-96f1-af18a224d17b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div[2]/form/div[2]/div[2]/div/div/div[1]/div[2]/div[1]/div[4]/div[1]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.view-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-line</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book    Chapter Verse   ID  SupportReference    OrigQuote   Occurrence  GLQuote OccurrenceNote</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-gitea&quot;]/body[1]/div[@class=&quot;full height&quot;]/div[@class=&quot;repository file editor edit&quot;]/div[@class=&quot;ui container&quot;]/form[@class=&quot;ui edit form dirty dirty-file&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui bottom attached active tab segment&quot;]/div[@class=&quot;monaco-editor-container&quot;]/div[@class=&quot;monaco-editor no-user-select mac  showUnused vs&quot;]/div[@class=&quot;overflow-guard&quot;]/div[@class=&quot;monaco-scrollable-element editor-scrollable vs mac&quot;]/div[@class=&quot;lines-content monaco-editor-background&quot;]/div[@class=&quot;view-lines&quot;]/div[@class=&quot;view-line&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview Changes'])[1]/following::div[117]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::div[117]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/div[4]/div</value>
   </webElementXpaths>
</WebElementEntity>
